"""Conversation Application Layer.

Contains use cases for orchestrating the conversation logic.
"""

from __future__ import annotations

from dataclasses import dataclass

from gubluu.conversation.domain import Conversation, LLMPort, Message, Role
from gubluu.core.events.bus import Event, EventBus
from gubluu.core.logging import get_logger

logger = get_logger(__name__)


@dataclass(frozen=True, kw_only=True)
class MessageGeneratedEvent(Event):
    """Event emitted when a new message is generated by the LLM."""
    conversation_id: str
    message: Message


class ChatUseCase:
    """Use case for handling a user message and getting an AI response."""

    def __init__(self, llm_port: LLMPort, event_bus: EventBus) -> None:
        self._llm = llm_port
        self._event_bus = event_bus

    async def handle_user_input(self, conversation: Conversation, text: str) -> Message:
        """Handle incoming text from the user.
        
        Args:
            conversation: The ongoing conversation state.
            text: The text the user entered.
            
        Returns:
            The generated assistant message.
        """
        user_message = Message(content=text, role=Role.USER)
        conversation.add_message(user_message)
        logger.debug("Added user message", conv_id=conversation.id)

        try:
            logger.info("Generating LLM response", conv_id=conversation.id)
            assistant_message = await self._llm.generate_response(conversation)
            conversation.add_message(assistant_message)
            
            # Publish event that the LLM spoke
            await self._event_bus.publish(
                MessageGeneratedEvent(
                    conversation_id=conversation.id,
                    message=assistant_message
                )
            )
            return assistant_message
        except Exception as e:
            logger.error("Failed to generate LLM response", error=str(e), conv_id=conversation.id)
            raise
